export type Status = 'adequado' | 'atencao' | 'critico'
export type CenarioTipo = 'pessimista' | 'realista' | 'otimista'

export * from './project'
export * from './production'
export * from './financial'
export * from './nutrition'
export * from './water'
export * from './licenses'
export * from './activities'
export * from './users'
